import os

cwd = os.getcwd()
env = Environment()

env.Append(CCFLAGS = ['-Wall'])
env.Append(LINKFLAGS = [''])
env.Append(LIBS = [''])
env.Append(CPPPATH = [os.path.join(cwd,'simpleini')])
env.Append(LIBPATH = [''])

src_files = Split("""
	  ConfigFile.cpp
	  """)
	
env.StaticLibrary(source = src_files, target = 'simpleini')
